export const desc = {
	ABT: 'Abbott Laboratories',
	ABBV: 'AbbVie Inc.',
	ACN: 'Accenture plc',
	GOOG: 'Alphabet Inc. (Google) Clase C',
	AMZN: 'Amazon.com, Inc.',
	AAPL: 'Apple Inc',
	BAC: 'Bank of America Corporation',
	'BRK.A': 'Berkshire Hathaway Inc.',
	BMY: 'Bristol-Myers Squibb Company',
	AVGO: 'Broadcom Inc.',
	CVX: 'Chevron Corporation',
	CSCO: 'Cisco Systems, Inc.',
	KO: 'Coca-Cola Company (The)',
	COST: 'Costco Wholesale Corporation',
	DHR: 'Danaher Corporation',
	LLY: 'Eli Lilly and Company',
	XOM: 'Exxon Mobil Corporation',
	HD: 'Home Depot, Inc. (The)',
	JNJ: 'Johnson & Johnson',
	JPM: 'JP Morgan Chase & Co.',
	MA: 'Mastercard Incorporated',
	MCD: 'McDonalds Corporation',
	MRK: 'Merck & Company, Inc.',
	META: 'Meta Platforms, Inc.',
	MSFT: 'Microsoft Corp.',
	MS: 'Morgan Stanley',
	NEE: 'NextEra Energy, Inc.',
	NKE: 'Nike, Inc.',
	NVDA: 'NVIDIA Corporation',
	ORCL: 'Oracle Corporation',
	PEP: 'PepsiCo, Inc.',
	PFE: 'Pfizer, Inc.',
	PM: 'Philip Morris International Inc',
	PG: 'Procter & Gamble Company (The)',
	CRM: 'Salesforce, Inc.',
	TSLA: 'Tesla, Inc.',
	TXN: 'Texas Instruments Incorporated',
	TMO: 'Thermo Fisher Scientific Inc',
	TMUS: 'T-Mobile US, Inc.',
	UPS: 'United Parcel Service, Inc.',
	UNH: 'UnitedHealth Group Incorporated',
	VZ: 'Verizon Communications Inc.',
	V: 'Visa Inc.',
	WMT: 'Walmart Inc.',
	DIS: 'Walt Disney Company (The)',
	WFC: 'Wells Fargo & Company',
};
